# Generated by Django 5.0.7 on 2024-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
