# Generated by Django 5.0.7 on 2024-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_contact_name_alter_contact_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='', max_length='50'),
        ),
    ]
